### ISSUE TITLE
What is the selection criteria of D in HSMM?

### ISSUE THREAD

**Issue by Wusir2018** [marytts/voice-cmu-nk-hsmm#1]
Hello,
Thank you for your open code!
What is the selection criteria for setting value of D? Why set D to maximum segment length in HSMM ?
If D is set as the maximum segment length, then the state corresponding to some smaller segment must also last for D time to jump to the next state? Compared with HMM, will the result be worse?
Could you help me?
Best wishes

**Comment by seblemaguer** [comment]
Hello,

sorry, could you indicate what do you mean by D or where it is defined?

**Comment by Wusir2018** [comment]
@seblemaguer 
Thank you for your reply！
I find some paper use $\lambda=[\pi, A, B, D]$ to denote the HSMM model. $A$ is a transition matrix denoting the probability of transition between hidden states, where $a_{ij}=p(z_{t} = j|z_{t-1} = i)$ is the probability from state $i$ at time $t-1$ to $j$ at time $t$, with the self-transition probability $a_{ii} = 0$. ${D}$ is presented the duration of the hidden state.

But I can't under stand how to choose the value of duration time.
Could you help me?
Than you very much!
reference: [https://www.cs.ubc.ca/~murphyk/Papers/segment.pdf](url)
[https://hal.inria.fr/hal-01115826/document](url)

**Comment by seblemaguer** [comment]
I didn't read the paper you gave, but in TTS, the key part of the HSMM is to model explicitly the duration sequence using Gaussians.  From this, D is defined as the set of distributions (one distribution per state) which models the duration in each state. This leads to remove the loops from the transition probability (so setting p_ii = 0) as the distribution D_i gives will give this duration.

So, D is not a parameter controlled by the user but trained by model. 

I suggest that you have a look at the following paper for a better description:

Zen, H., Tokuda, K., Masuko, T., Kobayasih, T., & Kitamura, T. (2007). A hidden semi-Markov model-based speech synthesis system. IEICE transactions on information and systems, 90(5), 825-834.

I close this issue as it is not related to MaryTTS or the present voice

**Comment by Wusir2018** [comment]
@seblemaguer 
Thank you very much! 👍
